SCREEN_SIZE = SCREENX, SCREENY = 320, 180

FPS = 60

PUSH_BACK_FORCE = 3

CAR_TURN_SPEED = 135
CAR_ACCELERATION = 5
CAR_POWER = 6
CAR_SIZE = 15

TRACK_FRICTION = 1
GRASS_FRICTION = 2*TRACK_FRICTION